version: 2
registries:
  npm-js:
    type: npm-registry
    url: https://registry.npmjs.org
    replaces-base: true
updates:
  # GH Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
  # node updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 10
      semver-major-days: 30
      semver-minor-days: 12
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'wrangler'
      - dependency-name: 'minify'
      - dependency-name: 'prettier'
