version: 2
registries:
  npm-registry:
    type: "npm-registry"
    url: "https://registry.npmjs.org"
    token: ${{secrets.GH_DUMMY}}
    replaces-base: true
updates:
  # node updates
  - package-ecosystem: "npm"
    registries:
      - npm-registry
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 10
      semver-major-days: 30
      semver-minor-days: 12
    groups:
      eslint:
        patterns:
          - "*eslint*"
          - "globals"
          - "jiti"
      hono:
        patterns:
          - "*hono*"
      atproto:
        patterns:
          - "@atproto/*"
      dev:
        patterns:
          - "toml"
          - "tsx"
          - "minify"
      auth:
        patterns:
          - "better-auth"
          - "drizzle-*"
    allow:
      - dependency-type: "production"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
    ignore:
      # A github action updates these for us
      - dependency-name: "wrangler"
      - dependency-name: "hono"
      # Ignore all of minify
      - dependency-name: "@types/minify"
      - dependency-name: "minify"
      # Always get patch and minor versions of node types
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
      # Ignore TSX's patches
      - dependency-name: "tsx"
        update-types:
          - "version-update:semver-patch"
      # We only use prettier for some nice formatting, ignore otherwise.
      - dependency-name: "prettier"
