name: Clear CF Cache

on:
  push:
    branches: ["main"]
    paths:
      - "assets/**"
      - "!assets/.assetsignore"
      - "!assets/_redirects"
      - "!assets/_headers"
      - "!assets/sitemap.xml"
      - "!assets/dep/original/**"
      - "!assets/.well-known/**"
      - "src/pages/**"
      - "src/statics/**"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  deployments: write

jobs:
  clean_deployments:
    name: Clean Previous Deploys
    uses: socksthewolf/workflows/.github/workflows/clean_deploys.yml@main
    secrets: inherit
    with:
      environment: cloudflare
  clear_cache:
    name: Clear Cloudflare Cache
    runs-on: ubuntu-latest
    environment: cloudflare
    steps:
      - name: Cloudflare Cache Cleaner
        uses: Cyb3r-Jak3/action-cloudflare-cache@6ebf798ade84e7ab7da249404e0c3b9aecf54f88
        with:
          zone: ${{ vars.CLOUDFLARE_ZONE }}
          api_token: ${{ secrets.CLOUDFLARE_TOKEN }}
          account_id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}

