name: Clear CF Cache

on:
  # run every year
  schedule:
    - cron: "5 0 1 1 *"
  push:
    branches: ["main"]
    paths-ignore:
    - ".github/**"
    - "README.md"
    - "LICENSE"
    - ".dev.vars*"
    - ".gitattributes"
    - ".markdownlint.json"
  workflow_dispatch:
    inputs:
      clear_cache:
          description: "Clear Cache"
          required: true
          type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  clear_cache:
    runs-on: ubuntu-latest
    continue-on-error: false
    environment:
      name: cloudflare
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
      - name: Cache Clean Check
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            cache_clear:
              - 'src/utils/appScripts.ts'
              - 'src/pages/**'
              - 'src/layout/helpers/**'
              - 'src/layout/fields/**'
              - 'assets/**'
              - '!assets/screenshots/**'
              - '!assets/.assetsignore'
      - name: Sleep for ~50 seconds
        if: success() && (steps.filter.outputs.cache_clear == 'true' || inputs.clear_cache == 'true' || github.event_name == 'schedule')
        # the average build/deploy will take about this amount of time
        run: sleep 50s
        shell: bash
      - name: Cloudflare Cache Cleaner
        uses: Cyb3r-Jak3/action-cloudflare-cache@6ebf798ade84e7ab7da249404e0c3b9aecf54f88
        if: steps.filter.outputs.cache_clear == 'true' || inputs.clear_cache == 'true' || github.event_name == 'schedule'
        with:
          zone: ${{ secrets.CLOUDFLARE_ZONE }}
          api_token: ${{ secrets.CLOUDFLARE_TOKEN }}
          account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
