# Cleans up previous GH action queues
name: Clean GH Actions

on:
  push:
    branches: ["main"]

concurrency:
  group: clean
  cancel-in-progress: false

permissions:
  actions: write

jobs:
  # Clean up github job
  clean_github:
    name: Remove Old Github Actions
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Actions
        uses: socksthewolf/gh-actions-clean-workflow@main
        with:
          token: ${{ secrets.GH_CLEANER_TOKEN }}
          runs_to_keep: 1
          runs_older_than: 0
