name: Build OpenAPI Spec

on:
  push:
    branches: ["main"]
    paths:
      - "src/endpoints/openapi.tsx"
      - "bin/openapi.ts"
  workflow_dispatch: {}

concurrency:
  group: openapi
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

jobs:
  clean_deploys:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Clean Old Github OpenAPI Deploys
    permissions:
      deployments: write
    steps:
      - name: Cleanup Previous Deploys
        uses: strumwolf/delete-deployment-environment@035f6d27c8b8951729f4d71b2d3d6a7975139476
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: openapi
          onlyRemoveDeployments: true

  build_spec:
    name: Update OpenAPI Data
    uses: socksthewolf/workflows/.github/workflows/openapi.yml@main
    secrets: inherit
    with:
      ref: ${{ github.ref }}
      needs_node: true
