name: Build OpenAPI Spec

on:
  push:
    branches: ["main"]
    paths:
      - "src/endpoints/openapi.tsx"
      - "bin/openapi.ts"
      - ".github/workflows/openapi.yml"
  workflow_dispatch: {}

concurrency:
  group: openapi
  cancel-in-progress: true

jobs:
  clean_deploys:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Clean Old Github OpenAPI Deploys
    permissions:
      deployments: write
    steps:
      - name: Cleanup Previous Deploys
        uses: strumwolf/delete-deployment-environment@035f6d27c8b8951729f4d71b2d3d6a7975139476
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: openapi
          onlyRemoveDeployments: true

  build_spec:
    name: Generate Spec
    runs-on: ubuntu-latest
    needs: clean_deploys
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          cache: "npm"
          node-version-file: ".node-version"
          package-manager-cache: true
      - name: Node Install Packages
        run: npm install
      - name: Run OpenAPI Gen
        run: npm run openapi
      - name: Upload Spec as Artifact
        if: success()
        uses: actions/upload-artifact@v7
        with:
          name: openapi-spec-${{ github.ref }}
          path: ./openapi.json
          archive: false
          if-no-files-found: error

  upload_spec:
    name: Upload Spec
    needs: build_spec
    runs-on: ubuntu-latest
    environment: openapi
    permissions:
      actions: read
    steps:
      - name: Download OpenAPI Spec
        uses: actions/download-artifact@v8
        with:
          name: openapi-spec-${{ github.ref }}
      - name: Upload Spec to WAF
        if: success()
        uses: socksthewolf/cloudflare-upload-spec@6d8c4c1ffd6972c0d1d1f1cf75ead06b6b313a49
        with:
          zone: ${{ vars.CLOUDFLARE_ZONE }}
          api_token: ${{ secrets.CLOUDFLARE_TOKEN }}
          file_name: openapi.json
          delete_others: true
