name: Force Rebuild Static Pages

on:
  # run every year (this will refresh the copyright date)
  schedule:
    - cron: "5 0 1 1 *"

  workflow_dispatch: {}

concurrency:
  group: static-pages
  cancel-in-progress: true

jobs:
  make_a_deploy:
    name: Make A Deploy
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    environment: cf-static-builds
    steps:
      # remove Github deployments
      - name: Cleanup Previous Deploys
        continue-on-error: true
        uses: strumwolf/delete-deployment-environment@035f6d27c8b8951729f4d71b2d3d6a7975139476
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: cf-static-builds
          onlyRemoveDeployments: true
      - name: Force CF Rebuild Using Action
        if: ${{ vars.USE_HOOK_DEPLOY == 'false' }}
        uses: socksthewolf/cloudflare-trigger-build@main
        with:
          account_id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          api_token: ${{ secrets.CLOUDFLARE_TOKEN }}
          worker_name: ${{ vars.CLOUDFLARE_WORKER_NAME }}
      - name: Force CF Rebuild Using Deploy Hook
        if: ${{ vars.USE_HOOK_DEPLOY == 'true' }}
        env:
          DEPLOY_HOOK: ${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}
        run: curl --no-progress-meter -X POST $DEPLOY_HOOK | jq -r ".success"