name: Force Rebuild Static Pages

on:
  # run every year (this will refresh the copyright date)
  schedule:
    - cron: "5 0 1 1 *"

  workflow_dispatch: {}

concurrency:
  group: static-pages
  cancel-in-progress: true

permissions:
  deployments: write

defaults:
  run:
    shell: bash

jobs:
  clean_deployments:
    name: Clean Previous Deploys
    uses: socksthewolf/workflows/.github/workflows/clean_deploys.yml@main
    secrets: inherit
    with:
      environment: cf-static-builds
  make_a_deploy:
    name: Make A Deploy
    runs-on: ubuntu-latest
    environment: cf-static-builds
    steps:
      - name: Force CF Rebuild
        env:
          DEPLOY_HOOK: ${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}
        run: curl --no-progress-meter -X POST $DEPLOY_HOOK | jq -r ".success"