name: Build & Update Sitemap
on:
  # check if the sitemap is up to date every sunday
  schedule:
    - cron: "0 1 * * 0"
  push:
    branches: ["main"]
    paths:
      - "src/pages/*.tsx"
      - "src/layout/main.tsx"
      - "src/layout/helpers/*.tsx"
      - ".github/workflows/sitemap.yml"
      - "!src/layout/helpers/uploadInfo.tsx"
      - "!src/layout/helpers/turnstile.tsx"
      - "!src/layout/helpers/includesTags.tsx"
      - "!assets/sitemap.xml"
  workflow_dispatch: {}

permissions:
  contents: write
  deployments: write

jobs:
  build_sitemap:
    uses: socksthewolf/workflows/.github/workflows/build_sitemap.yml@main
    secrets: inherit
    with:
      clean_deploys: true
      live_url: https://skyscheduler.work/sitemap.xml
      path: "assets/sitemap.xml"

  update_tangled:
    needs: build_sitemap
    if: ${{ needs.build_sitemap.outputs.had_changes == 'true' }}
    uses: socksthewolf/workflows/.github/workflows/deploy_tangled.yml@main
    secrets: inherit