# Mirror everything to Tangled
name: Tangled Bangled

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  deployments: write

jobs:
  push_tangled:
    name: Update Tangled Mirror
    runs-on: ubuntu-latest
    environment:
      name: tangled
    steps:
      - name: Push to Tangled
        uses: gwennlbh/to-tangled@50f70a6910307e6fffa632e6d7cfec6b9e9f94ec
        with:
          repo: ${{ vars.MIRROR_REPO }}
          ssh-key: ${{ secrets.KEY }}
      - name: Cleanup Previous Deploys
        if: success()
        uses: strumwolf/delete-deployment-environment@035f6d27c8b8951729f4d71b2d3d6a7975139476
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: tangled
          onlyRemoveDeployments: true
