# Mirror everything to Tangled
name: Tangled Bangled

on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    environment:
      name: tangled
    steps:
      - name: Push to Tangled
        uses: gwennlbh/to-tangled@v0.4
        with:
          repo: socksthewolf.com/skyscheduler
          ssh-key: ${{ secrets.KEY }}