# Mirror everything to Tangled
name: Tangled Bangled

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    environment:
      name: tangled
    steps:
      - name: Push to Tangled
        uses: gwennlbh/to-tangled@50f70a6910307e6fffa632e6d7cfec6b9e9f94ec
        with:
          repo: ${{ vars.MIRROR_REPO }}
          ssh-key: ${{ secrets.KEY }}
